### ISSUE TITLE
Thinking Sphinx?

### ISSUE THREAD

**Issue by atif** [mauricio/master_slave_adapter#4]
Is this plugin compatible with a project having thinking sphinx enabled? I'm currently facing an exception:

**\* Exception!!! (StandardError) undefined method `unique_transaction_key' for #<ActiveRecord::ConnectionAdapters::MysqlAdap
ter:0x9cce594> ***

The plugin seems to have a conflict with after commit, and thinking sphinx i guess.

Any idea?

Thanks,
Atif Dastgir

**Comment by mauricio** [comment]
When you disable it the error disappears? This looks like a MySQL adapter error.
